version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./AppServer
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000